In [59]:
EXPER_PATH = '/root/Internship-Valeo/Project/exports'

In [60]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

import evaluations.descriptor_evaluation as ev
from plot_utils import plot_imgs
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
def draw_matches(data):
    keypoints1 = [cv2.KeyPoint(p[1], p[0], 1) for p in data['keypoints1']]
    keypoints2 = [cv2.KeyPoint(p[1], p[0], 1) for p in data['keypoints2']]
    inliers = data['inliers'].astype(bool)
    matches = np.array(data['matches'])[inliers].tolist()
    img1 = np.concatenate([output['image1'], output['image1'], output['image1']], axis=2) * 255
    img2 = np.concatenate([output['image2'], output['image2'], output['image2']], axis=2) * 255
    return cv2.drawMatches(img1, keypoints1, img2, keypoints2, matches,
                           None, matchColor=(0,255,0), singlePointColor=(0, 0, 255))

# Changes in viewpoint

In [62]:
# experiments = ['sp_v6_desc_hp_v', 'magic_leap_pretrained_model_desc_hp_v', 'sift_desc_hp_v', 'orb_desc_hp_v']
experiments = ['superpoint_hpatches-v']

### Images visualization

In [63]:
num_images = 2
for e in experiments:
    orb = True if e[:3] == 'orb' else False
    outputs = ev.get_homography_matches(e, keep_k_points=1000, correctness_thresh=3, num_images=num_images, orb=orb)
    for output in outputs:
        img = draw_matches(output) / 255.
        plot_imgs([img], titles=[e], dpi=200)

[[ 3.6889648e-01  4.0283203e-03  4.3225000e+02]
 [ 1.2242794e-04  3.7280273e-01  2.6375000e+02]
 [-4.3469481e-07  5.5953860e-06  1.0000000e+00]]
[[ 2.70941496e+00 -1.17454045e-02 -1.16804675e+03]
 [-1.72986253e-03  2.69305205e+00 -7.09544739e+02]
 [ 1.18744788e-06 -1.50737715e-05  1.00346243e+00]]
[[ 1.4273127e+00 -4.8244003e-02  1.7793442e+02]
 [ 3.9941263e-01  1.2520803e+00 -5.1676160e+02]
 [ 3.0401064e-04 -2.1614751e-05  1.0000000e+00]]
[[ 7.1780807e-01  2.5682138e-02 -1.1445122e+02]
 [-3.2191682e-01  7.9434210e-01  4.6776556e+02]
 [-2.2517945e-04  9.3618628e-06  1.0449051e+00]]


AttributeError: 'list' object has no attribute 'astype'

### Homography estimation correctness

In [ ]:
for exp in experiments:
    orb = True if exp[:3] == 'orb' else False
    correctness = ev.homography_estimation(exp, keep_k_points=1000, correctness_thresh=3, orb=orb)
    print('> {}: {}'.format(exp, correctness))

### Check that the image is warped correctly

In [ ]:
num_images = 2
for e in experiments:
    orb = True if e[:3] == 'orb' else False
    outputs = ev.get_homography_matches(e, keep_k_points=1000, correctness_thresh=3, num_images=num_images, orb=orb)
    for output in outputs:
        img1 = output['image1'] * 255
        img2 = output['image2'] * 255
        H = output['homography']
        warped_img1 = cv2.warpPerspective(img1, H, (img2.shape[1], img2.shape[0]))
        img1 = np.concatenate([img1, img1, img1], axis=2)
        warped_img1 = np.stack([warped_img1, warped_img1, warped_img1], axis=2)
        img2 = np.concatenate([img2, img2, img2], axis=2)
        plot_imgs([img1 / 255., img2 / 255., warped_img1 / 255.], titles=['img1', 'img2', 'warped_img1'], dpi=200)

# Changes in illumination

In [ ]:
# experiments = ['sp_v6_desc_hp_i', 'magic_leap_pretrained_model_desc_hp_i', 'sift_desc_hp_i', 'orb_desc_hp_i']
experiments = ['superpoint_hpatches-i']

### Images visualization

In [ ]:
num_images = 2
for e in experiments:
    orb = True if e[:3] == 'orb' else False
    outputs = ev.get_homography_matches(e, keep_k_points=1000, correctness_thresh=3, num_images=num_images, orb=orb)
    for output in outputs:
        img = draw_matches(output) / 255.
        plot_imgs([img], titles=[e], dpi=200, cmap='gray')

### Homography estimation correctness

In [ ]:
for exp in experiments:
    orb = True if exp[:3] == 'orb' else False
    correctness = ev.homography_estimation(exp, keep_k_points=1000, correctness_thresh=3, orb=orb)
    print('> {}: {}'.format(exp, correctness))

# All changes

In [ ]:
# experiments = ['sp_v6_desc_hp_all', 'magic_leap_pretrained_model_desc_hp_all', 'sift_desc_hp_all', 'orb_desc_hp_all']

In [ ]:
thresholds = [1, 3, 5]
for thresh in thresholds:
    print("Correctness threshold = " + str(thresh) + ":")
    for exp in experiments:
        orb = True if exp[:3] == 'orb' else False
        correctness = ev.homography_estimation(exp, keep_k_points=1000, correctness_thresh=thresh, orb=orb)
        print('> {}: {}'.format(exp, correctness))

In [ ]:
experiments = ['superpoint_hpatches-all']

In [ ]:
thresholds = [1, 3, 5]
for thresh in thresholds:
    print("Correctness threshold = " + str(thresh) + ":")
    for exp in experiments:
        orb = True if exp[:3] == 'orb' else False
        correctness = ev.homography_estimation(exp, keep_k_points=1000, correctness_thresh=thresh, orb=orb)
        print('> {}: {}'.format(exp, correctness))